[project]
name = "roboticsproject2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.1",
    "picamera2>=0.3.25",
    "ultralytics>=8.3.94",
]
